#!/bin/bash

# Replace '@DEFAULT_SINK@' with your specific sink ID or name
# sink="0"  # or use "alsa_output.pci-0000_00_1b.0.analog-stereo" # This changes after rebooting,
# better using the alternative right down here:
sink=$(pactl info | grep "Default Sink" | awk '{print $3}')

# Get the current volume and mute status using pactl
volume=$(pactl get-sink-volume "$sink" | grep -oP '\d+%' | head -n 1)
mute_status=$(pactl get-sink-mute "$sink" | grep -o "yes")

# Check if muted
if [ "$mute_status" = "yes" ]; then
    echo "Muted"
else
    echo "$volume"
fi

